/**
 * List of allo Action Ids supported in Kibo
 */
export enum ActionId {
  "embedded.commerce.carts.addItem.after",
  "embedded.commerce.carts.addItem.before",
  "embedded.commerce.carts.deleteCart.after",
  "embedded.commerce.carts.deleteCart.before",
  "embedded.commerce.carts.deleteItem.after",
  "embedded.commerce.carts.deleteItem.before",
  "embedded.commerce.carts.get.after",
  "embedded.commerce.carts.updateItem.after",
  "embedded.commerce.carts.updateItem.before",
  "embedded.commerce.catalog.storefront.products.getPriceListHierachy",
  "embedded.commerce.checkouts.createFromCart.after",
  "embedded.commerce.checkouts.createfromcart.before",
  "embedded.commerce.checkouts.groupings.after",
  "embedded.commerce.checkouts.itemdestinationupdate.after",
  "embedded.commerce.checkouts.price.after",
  "embedded.commerce.checkouts.price.before",
  "embedded.commerce.customer.accounts.verifyExternalPassword",
  "embedded.commerce.orders.action.after",
  "embedded.commerce.orders.action.before",
  "embedded.commerce.orders.addItem.after",
  "embedded.commerce.orders.addItem.before",
  "embedded.commerce.orders.createFromCart.after",
  "embedded.commerce.orders.createFromCart.before",
  "embedded.commerce.orders.deleteItem.after",
  "embedded.commerce.orders.deleteItem.before",
  "embedded.commerce.orders.price.after",
  "embedded.commerce.orders.price.before",
  "embedded.commerce.payments.action.after",
  "embedded.commerce.payments.action.before",
  "embedded.commerce.payments.action.performPaymentInteraction",
  "embedded.commerce.return.GetRmaLabels.after",
  "embedded.commerce.return.GetRmaLabels.before",
  "embedded.commerce.return.actions.after",
  "embedded.commerce.return.actions.before",
  "embedded.commerce.return.retrieveReasons",
  "embedded.platform.applications.install",
  "embedded.platform.applications.uninstall",
  "http.commerce.catalog.admin.categories.addCategory.after",
  "http.commerce.catalog.admin.categories.addCategory.before",
  "http.commerce.catalog.admin.categories.updateCategory.after",
  "http.commerce.catalog.admin.categories.updateCategory.before",
  "http.commerce.catalog.admin.products.updateProduct.after",
  "http.commerce.catalog.admin.products.updateProduct.before",
  "http.commerce.catalog.storefront.pricing.priceOrder.after",
  "http.commerce.catalog.storefront.pricing.priceOrder.before",
  "http.commerce.catalog.storefront.pricing.priceProduct.after",
  "http.commerce.catalog.storefront.pricing.priceProduct.before",
  "http.commerce.catalog.storefront.pricing.priceProducts.after",
  "http.commerce.catalog.storefront.pricing.priceProducts.before",
  "http.commerce.catalog.storefront.pricing.repriceOrder.after",
  "http.commerce.catalog.storefront.pricing.repriceOrder.before",
  "http.commerce.catalog.storefront.products.configuredProduct.after",
  "http.commerce.catalog.storefront.products.configuredProduct.before",
  "http.commerce.catalog.storefront.products.getProduct.after",
  "http.commerce.catalog.storefront.products.getProduct.before",
  "http.commerce.catalog.storefront.products.getProductForIndexing.after",
  "http.commerce.catalog.storefront.products.getProductForIndexing.before",
  "http.commerce.catalog.storefront.products.getProducts.after",
  "http.commerce.catalog.storefront.products.getProducts.before",
  "http.commerce.catalog.storefront.products.locationinventories.after",
  "http.commerce.catalog.storefront.products.locationinventories.before",
  "http.commerce.catalog.storefront.products.resolvePriceList.after",
  "http.commerce.catalog.storefront.products.resolvePriceList.before",
  "http.commerce.catalog.storefront.products.validateProduct.after",
  "http.commerce.catalog.storefront.products.validateProduct.before",
  "http.commerce.catalog.storefront.productsearch.search.after",
  "http.commerce.catalog.storefront.productsearch.search.before",
  "http.commerce.catalog.storefront.shipping.requestRates.after",
  "http.commerce.catalog.storefront.shipping.requestRates.before",
  "http.commerce.catalog.storefront.tax.estimateTaxes.after",
  "http.commerce.catalog.storefront.tax.estimateTaxes.before",
  "http.commerce.checkouts.addDestination.after",
  "http.commerce.checkouts.addDestination.before",
  "http.commerce.checkouts.updateDestination.after",
  "http.commerce.checkouts.updateDestination.before",
  "http.commerce.customer.accounts.addAccount.after",
  "http.commerce.customer.accounts.addAccount.before",
  "http.commerce.customer.accounts.addAccountAndLogin.after",
  "http.commerce.customer.accounts.addAccountAndLogin.before",
  "http.commerce.customer.accounts.changePassword.after",
  "http.commerce.customer.accounts.changePassword.before",
  "http.commerce.customer.accounts.updateAccount.after",
  "http.commerce.customer.accounts.updateAccount.before",
  "http.commerce.customer.accounts.updateForgottenPassword.after",
  "http.commerce.customer.accounts.updateForgottenPassword.before",
  "http.commerce.customer.address.validation.after",
  "http.commerce.customer.address.validation.before",
  "http.commerce.customer.authTickets.createUserAuthTicket.after",
  "http.commerce.customer.authTickets.createUserAuthTicket.before",
  "http.commerce.customer.credits.addCredit.after",
  "http.commerce.customer.credits.addCredit.before",
  "http.commerce.customer.credits.addTransaction.after",
  "http.commerce.customer.credits.addTransaction.before",
  "http.commerce.customer.credits.associateCreditToShopper.after",
  "http.commerce.customer.credits.associateCreditToShopper.before",
  "http.commerce.customer.credits.deleteCredit.before",
  "http.commerce.customer.credits.getAuditEntries.after",
  "http.commerce.customer.credits.getAuditEntries.before",
  "http.commerce.customer.credits.getCredit.after",
  "http.commerce.customer.credits.getCredit.before",
  "http.commerce.customer.credits.getCredits.after",
  "http.commerce.customer.credits.getCredits.before",
  "http.commerce.customer.credits.getTransactions.after",
  "http.commerce.customer.credits.getTransactions.before",
  "http.commerce.customer.credits.resendCreditCreatedEmail.before",
  "http.commerce.customer.credits.updateCredit.after",
  "http.commerce.customer.credits.updateCredit.before",
  "http.commerce.orders.setBillingInfo.after",
  "http.commerce.orders.setBillingInfo.before",
  "http.commerce.orders.setFulFillmentInfo.after",
  "http.commerce.orders.setFulFillmentInfo.before",
  "http.commerce.returns.createPackage.after",
  "http.commerce.returns.createPackage.before",
  "http.commerce.returns.createPackageShipments.after",
  "http.commerce.returns.createPackageShipments.before",
  "http.commerce.returns.createReturnItem.after",
  "http.commerce.returns.createReturnItem.before",
  "http.commerce.returns.deleteOrderItem.after",
  "http.commerce.returns.deleteOrderItem.before",
  "http.commerce.returns.deletePackage.after",
  "http.commerce.returns.deletePackage.before",
  "http.commerce.returns.deleteReturn.after",
  "http.commerce.returns.deleteReturn.before",
  "http.commerce.returns.deleteShipment.after",
  "http.commerce.returns.deleteShipment.before",
  "http.commerce.returns.updatePackage.after",
  "http.commerce.returns.updatePackage.before",
  "http.commerce.returns.updateReturn.after",
  "http.commerce.returns.updateReturn.before",
  "http.commerce.settings.checkout.paymentsettings.updatePaymentSettings.before",
  "http.storefront.pages.404.request.after",
  "http.storefront.pages.404.request.before",
  "http.storefront.pages.cart.request.after",
  "http.storefront.pages.cart.request.before",
  "http.storefront.pages.category.request.after",
  "http.storefront.pages.category.request.before",
  "http.storefront.pages.checkout.request.after",
  "http.storefront.pages.checkout.request.before",
  "http.storefront.pages.cmspage.request.after",
  "http.storefront.pages.cmspage.request.before",
  "http.storefront.pages.global.request.after",
  "http.storefront.pages.global.request.before",
  "http.storefront.pages.myAccount.request.after",
  "http.storefront.pages.myAccount.request.before",
  "http.storefront.pages.orderConfirmation.request.after",
  "http.storefront.pages.orderConfirmation.request.before",
  "http.storefront.pages.productDetails.request.after",
  "http.storefront.pages.productDetails.request.before",
  "http.storefront.pages.search.request.after",
  "http.storefront.pages.search.request.before",
  "http.storefront.routes",
}

export interface ArcFunction {
  actionName: ActionId;
  customFunction: (
    context: any,
    callback: (errorMessage?: string) => void
  ) => void;
}

export function createArcFunction(
  actionName: ActionId,
  customFunction: (
    context: any,
    callback: (errorMessage?: string) => void
  ) => void
): ArcFunction {
  return { actionName: actionName, customFunction: customFunction };
}
